### ISSUE TITLE
getUserInfo() doesn't work for Cexio anymore

### ISSUE THREAD

**Issue by nickyharpor** [Poryaei/All-In-One#10]
Cexio's thread logs this exception recently:

```
Exception in thread Thread-1 (do_tasks):
Traceback (most recent call last):
  File "All-In-One/venv/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "All-In-One/scripts/cexio.py", line 193, in do_tasks
    r = self.getUserInfo()
  File "All-In-One/scripts/cexio.py", line 40, in getUserInfo
    ).json()
  File "All-In-One/venv/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by nickyharpor** [comment]
My bad. This has nothing to do with the code. Cexio's server was down.
