### ISSUE TITLE
Error Cex IO

### ISSUE THREAD

**Issue by xDaijobu** [Poryaei/All-In-One#14]
Hello there,

Thank you so much for creating this bot. I have encountered an error and need your help.

```
INFO     | mainapp | Client is Ready!
INFO     | TapSwap | [~] ByPass CHQ:  1154
INFO     | TapSwap | Auth Token fetched successfully.
INFO     | Hamster | Auth Token fetched successfully.
Exception in thread Thread-1 (do_tasks):
Traceback (most recent call last):
  File "D:\Cris\airdrop\taptap\All-In-One\venv\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "D:\Cris\airdrop\taptap\All-In-One\venv\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\UseR\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Cris\airdrop\taptap\All-In-One\venv\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "D:\Cris\airdrop\taptap\All-In-One\venv\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\Cris\airdrop\taptap\All-In-One\venv\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\Cris\airdrop\taptap\All-In-One\venv\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "D:\Cris\airdrop\taptap\All-In-One\venv\lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "D:\Cris\airdrop\taptap\All-In-One\venv\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000002BB1F6905B0>: Failed to resolve 'cexp.cex.io' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Cris\airdrop\taptap\All-In-One\venv\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\Cris\airdrop\taptap\All-In-One\venv\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "D:\Cris\airdrop\taptap\All-In-One\venv\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cexp.cex.io', port=443): Max retries exceeded with url: /api/getUserInfo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002BB1F6905B0>: Failed to resolve 'cexp.cex.io' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UseR\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\UseR\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Cris\airdrop\taptap\All-In-One\scripts\cexio.py", line 193, in do_tasks
    r = self.getUserInfo()
  File "D:\Cris\airdrop\taptap\All-In-One\scripts\cexio.py", line 37, in getUserInfo
    r = self.session.post(
  File "D:\Cris\airdrop\taptap\All-In-One\venv\lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "D:\Cris\airdrop\taptap\All-In-One\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Cris\airdrop\taptap\All-In-One\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Cris\airdrop\taptap\All-In-One\venv\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cexp.cex.io', port=443): Max retries exceeded with url: /api/getUserInfo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002BB1F6905B0>: Failed to resolve 'cexp.cex.io' ([Errno 11001] getaddrinfo failed)"))```
```
![image](https://github.com/Poryaei/All-In-One/assets/22674537/8987f2ae-8873-4812-94ae-ec6745492a6a)

**Comment by Poryaei** [comment]
I think the problem must be with your network! 🤔
