### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException

### ISSUE THREAD

**Issue by mrdarkerr** [Poryaei/All-In-One#24]
python3 multi-account.py
Traceback (most recent call last):
  File "/root/All-In-One/venv/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 3862, in get_local_driver
    driver = webdriver.Chrome(options=chrome_options)
  File "/root/All-In-One/venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/root/All-In-One/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/root/All-In-One/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/root/All-In-One/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/All-In-One/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/All-In-One/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /root/.cache/selenium/chrome/linux64/126.0.6478.61/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55fc3da9b6aa <unknown>
#1 0x55fc3d77e0dc <unknown>
#2 0x55fc3d7b302a <unknown>
#3 0x55fc3d7af43b <unknown>
#4 0x55fc3d7f9ef9 <unknown>
#5 0x55fc3d7ed613 <unknown>
#6 0x55fc3d7bd4f7 <unknown>
#7 0x55fc3d7bde4e <unknown>
#8 0x55fc3da6187b <unknown>
#9 0x55fc3da65921 <unknown>
#10 0x55fc3da4d36e <unknown>
#11 0x55fc3da66482 <unknown>
#12 0x55fc3da31ccf <unknown>
#13 0x55fc3da8b0a8 <unknown>
#14 0x55fc3da8b280 <unknown>
#15 0x55fc3da9a7dc <unknown>
#16 0x7f2cfb12aac3 <unknown>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/All-In-One/multi-account.py", line 10, in <module>
    from scripts.bypass_js  import driver_instance
  File "/root/All-In-One/scripts/bypass_js.py", line 66, in <module>
    driver_instance = SingletonDriver()
  File "/root/All-In-One/scripts/bypass_js.py", line 13, in __new__
    cls._instance.driver_context = DriverContext()
  File "/root/All-In-One/venv/lib/python3.10/site-packages/seleniumbase/plugins/driver_manager.py", line 44, in __init__
    self.driver = Driver(*args, **kwargs)
  File "/root/All-In-One/venv/lib/python3.10/site-packages/seleniumbase/plugins/driver_manager.py", line 529, in Driver
    driver = browser_launcher.get_driver(
  File "/root/All-In-One/venv/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 1657, in get_driver
    return get_local_driver(
  File "/root/All-In-One/venv/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 3944, in get_local_driver
    driver = webdriver.Chrome(
  File "/root/All-In-One/venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/root/All-In-One/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/root/All-In-One/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/root/All-In-One/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/All-In-One/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/All-In-One/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /root/.cache/selenium/chrome/linux64/126.0.6478.61/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5623287a46aa <unknown>
#1 0x5623284870dc <unknown>
#2 0x5623284bc02a <unknown>
#3 0x5623284b843b <unknown>
#4 0x562328502ef9 <unknown>
#5 0x5623284f6613 <unknown>
#6 0x5623284c64f7 <unknown>
#7 0x5623284c6e4e <unknown>
#8 0x56232876a87b <unknown>
#9 0x56232876e921 <unknown>
#10 0x56232875636e <unknown>
#11 0x56232876f482 <unknown>
#12 0x56232873accf <unknown>
#13 0x5623287940a8 <unknown>
#14 0x562328794280 <unknown>
#15 0x5623287a37dc <unknown>
#16 0x7fbb41296ac3 <unknown>
Exception ignored in: <function SingletonDriver.__del__ at 0x7f144dc71870>
Traceback (most recent call last):
  File "/root/All-In-One/scripts/bypass_js.py", line 63, in __del__
AttributeError: 'SingletonDriver' object has no attribute 'driver_context'

**Comment by Poryaei** [comment]
Please update the code. 🔄
